In [1]:
import tensorflow as tf

In [2]:
#tf.Operation and tf.Tensor
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [3]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [4]:
tf.print(a.numpy()[0])

2


In [5]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms
    print(c)
    return c

In [6]:
result = add(a,b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


In [7]:
Scalar = tf.constant(2)
Vector = tf.constant([5, 6, 2])
Matrix = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
Tensor = tf.constant( [ [[1, 2, 3], [2, 3, 4], [3, 4, 5]], [[4, 5, 6], [5, 6, 7], [6, 7, 8]], [[7, 8, 9], [8, 9, 10], [9, 10, 11]] ] )

print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries):\n %s \n" % Vector)

print ("Matrix (3*3 entries):\n %s \n" % Matrix)

print ("Tensor (3*3*3 entries):\n %s \n" % Tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries):
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3*3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 

Tensor (3*3*3 entries):
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [8]:
#tf.shape returns the shape of our data structure

In [9]:
Scalar.shape

TensorShape([])

In [10]:
Tensor.shape

TensorShape([3, 3, 3])

In [12]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

@tf.function
def add():
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    return add_1_operation

print ("Defined using tensorflow function :")
add_1_operation = add()
print ("Defined using normal expressions :")
add_2_operation = Matrix_one + Matrix_two
print(add_2_operation)

Defined using tensorflow function :
Defined using normal expressions :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [15]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

@tf.function
def mathmul():
    return tf.matmul(Matrix_one, Matrix_two)
mul_operation = mathmul()

print("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


In [17]:
#Variables 
v = tf.Variable(0)

In [18]:
@tf.function
def increment_by_one(v):
        v = tf.add(v,1)
        return v

In [19]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [21]:
#Operation include functions like (tf.constant, tf.matmul, tf.add, while tf.nn.sigmoid is an activation function)
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

print('c =: %s' % c)

print('d =: %s' % d)

c =: tf.Tensor([7], shape=(1,), dtype=int32)
d =: tf.Tensor([3], shape=(1,), dtype=int32)
